url: "http://projects.flo.by/node-stream-stream"
pygments: true
exclude: [/bin, Gemfile, Gemfile.lock]
markdown: redcarpet
#markdown: kramdown
#markdown: rdiscount
permalink: pretty
paginate: 5
project: node-stream-stream
project_image: /images/node-stream-stream-icon.png
menu_item: projects
title: node-stream-stream
submenu:
    - slug: home
      name: Home
      link: '/'

    - slug: download
      name: Download
      link: '/download'

    - slug: readme
      name: Read me
      link: '/readme'

kramdown:
  entity_output: symbolic
rdiscount:
  entity_output: symbolic
redcarpet:
  entity_output: symbolic
